[setup.limitador]
url = "http://localhost"
port = 8080
ticker = 1

[ratelimit]
namespace = "default"
gateways = 3
listeners = 15
cleanup = true
order = ["gateway", "route", "rlp", "route-rlp"]
workers = 1

# [auth]
# namespace = "default"
# gateways = 1
# listeners = 30
# cleanup = true
# order = ["gateway", "route", "auth", "route-auth"]
# workers = 2

# [all]
# namespace = "default"
# gateways = 2
# listeners = 15
# cleanup = true
# order = ["gateway", "route", "auth", "rlp", "route-auth", "route-rlp"]
# workers = 2
