[test-1]
namespace = "default"
gateways = 1
listeners = 7
cleanup = true
order = ["gateway", "route", "rlp", "route-rlp"]
workers = 1
#
# [test-2]
# namespace = "default"
# gateways = 1
# listeners = 2
# cleanup = true
# order = ["gateway", "rlp", "route", "route-rlp"]
# workers = 3
#
# [test-3]
# namespace = "default"
# gateways = 1
# listeners = 2
# cleanup = true
# order = ["gateway", "route", "rlp", "route-rlp"]

# [large]
# namespace = "default"
# gateways = 1
# listeners = 63
# cleanup = true
# order = ["gateway", "route", "rlp", "route-rlp"]
