[test-1]
namespace = "default"
gateways = 1
listeners = 2
cleanup = true
order = ["gateway", "route", "rlp"]
workers = 2

[test-2]
namespace = "default"
gateways = 1
listeners = 2
cleanup = true
order = ["gateway", "route", "route-rlp"]
workers = 3

[test-3]
namespace = "default"
gateways = 1
listeners = 2
cleanup = true
order = ["gateway", "route", "rlp", "route-rlp"]
